language: php
php:
  - nightly
  - 7.1
  - 7.0
matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - COMPOSER_ROOT_VERSION=dev-master composer update --no-interaction --prefer-dist
  - COMPOSER_ROOT_VERSION=dev-master composer require --dev codeclimate/php-test-reporter:dev-master
  - if [[ $TRAVIS_PHP_VERSION == *hhvm* ]]; then
      sudo printf "zend.assertions = 1;\n" >> /etc/hhvm/php.ini;
    else
      phpenv config-add .travis.php.ini;
    fi

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=6241b92d584e4828e3489c526c6f5a73d47a0a5ec5479d074bbaeeb5d5a649dd ./vendor/bin/test-reporter